### ISSUE TITLE
PhoneGap Build - Android error [delete]

### ISSUE THREAD

**Issue by Mhitra** [dialogflow/dialogflow-cordova-client#21] opened 2016-07-21 04:02 UTC
Hi,
I have tried to compile my Cordova Project to Android and IOS from PhoneGap Build website.

For IOS no problem, but for Android, PhoneGap can not compile because of this issue:
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: ApiAiPlugin.java

Can you help me please to figure out this issue?
Thank you

PS I'm using the last version 1.7.4

**Comment by xVir** [comment] 2016-07-21 07:25
Hi! 

The problem related only to PhoneGap Build website or the project compilation fails on your PC also?

Thanks

**Comment by r4nm4** [comment] 2016-07-22 02:27
Hi @xVir 
The problem is related only to PhoneGap Build website, from command line (I'm using Ionic) works fine.
Thanks

**Comment by xVir** [comment] 2016-07-25 12:50
Hi! 
I tried to build the https://github.com/api-ai/api-ai-cordova-sample and it seems it built successfully.

Here is the log
[build.txt](https://github.com/api-ai/api-ai-cordova/files/381518/build.txt)

So, could you please attach log of your build process?

Thanks.

**Comment by r4nm4** [comment] 2016-07-25 22:46
Hi @xVir ,
thank you for your help, here my PhoneGap log with my error:
(Only a stupid question, is it possible I have this issue because my project use Ionic?)

:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResourcesWarning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

:generateDebugSources
:compileDebugJava/project/src/ai/api/ApiAiPlugin.java:139: error: cannot find symbol
            if(!cordova.hasPermission(RECORD_AUDIO)) {
                       ^
  symbol:   method hasPermission(String)
  location: variable cordova of type CordovaInterface
/project/src/ai/api/ApiAiPlugin.java:258: error: cannot find symbol
        cordova.requestPermission(this, requestCode, RECORD_AUDIO);
               ^
  symbol:   method requestPermission(ApiAiPlugin,int,String)
  location: variable cordova of type CordovaInterface
/project/src/ai/api/ApiAiPlugin.java:408: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
 FAILED

FAILURE: Build failed with an exception.

**Comment by xVir** [comment] 2016-07-26 08:42
Hi! 
It is strange, I've just checked my sample https://github.com/xVir/api-ai-ionic-sample and it is compiled without errors.

So, could you please take a look at https://github.com/xVir/api-ai-ionic-sample/blob/master/config.xml and  https://github.com/xVir/api-ai-ionic-sample/blob/master/package.json ?

May be you will notice some differences with your project configuration...

**Comment by r4nm4** [comment] 2016-07-27 04:29
Hi @xVir ,
yes, both files are different, but only because I have like 15 plugins.
Maybe someone make some conflict.
I will investigate about that in the future and I will try to add 1 by 1 the another pluging.
Unfortunately I can not do that soon because I decided to use API.AI service with external API and not with cordova.
Thank you for your time and your great job.

**Comment by xVir** [comment] 2016-07-27 08:53
Hi! 
Thanks!

Feel free to ask any questions.

**Comment by r4nm4** [comment] 2016-07-27 09:11
Thank you for your kindness :)
I will update this ticket soon I can.

**Closed** 2022-04-26 22:19 UTC
